### ISSUE TITLE
run demo.py problem

### ISSUE THREAD

**Issue by 930083287** [JunjH/Revisiting_Single_Depth_Estimation#19]
use senet154 model
input img:
![image](https://user-images.githubusercontent.com/15224527/58676485-0a6b2e80-838b-11e9-9545-7839939dc165.png)
output result:
![image](https://user-images.githubusercontent.com/15224527/58676532-28389380-838b-11e9-967f-606f2c323eb3.png)
I feel this result is not normal.How can I present the following results?
![image](https://user-images.githubusercontent.com/15224527/58676591-67ff7b00-838b-11e9-8f04-2d6aaf47850b.png)

**Comment by Hackerlil** [comment]
In demo.py ,looks that your model's output depth map is not so big,just 114x152 compares to input image of nyuv2 is 640x480,maybe you should resize input image into 114x152
