### ISSUE TITLE
Dataset about Depth Inpainting

### ISSUE THREAD

**Issue by FZH92128** [JunjH/Revisiting_Single_Depth_Estimation#23]
Hi, Junjie:
Your work is very inspiring and I want to know how you get the preprocessed dataset(depth image) you provide. My situation is that there are many black blocks in my processed dataset ( depth image)but I find that the depth images in your training data  are very smooth. Could you please tell me how can I process the raw data to abttain the ones like yours?

**Comment by JunjH** [comment]
You can download the official toolbox from the nyu-v2 homepage for depth completion.

**Comment by youzunzhi** [comment]
> You can download the official toolbox from the nyu-v2 homepage for depth completion.

@JunjH Did you use the toolbox to get your data? Or you just downloaded it somewhere else?
