### ISSUE TITLE
Missing Info on how the pre-trained models are saved

### ISSUE THREAD

**Issue by AnushaManila** [JunjH/Revisiting_Single_Depth_Estimation#25]
![pretrained](https://user-images.githubusercontent.com/12676003/68506597-d3912280-021e-11ea-9aff-4a5ba22802aa.png)
First of all, Thanks for sharing your work.
The downloadable pre-trained models can be used straight away for depth prediction. 
However, after re-training the model from scratch and while loading the self-trained model, the generated checkpoint.pth.tar has "Missing and Unexpected keys" in state_dict. Could you elaborate on how the models in the rectangle above "Program (application/octet-stream)" format are saved? 

(If I load the model with strict=False, the generated result doesn't match the result obtained from the pre-trained model.)

**Comment by Sekunde** [comment]
i think it is sort of related to torch.nn.DataParallel, if you load model before DataParallel in test.py, maybe it works out.
