### ISSUE TITLE
About the loss function

### ISSUE THREAD

**Issue by Yidoudoujiang** [JunjH/Revisiting_Single_Depth_Estimation#27]
Thanks for your code ! But when I run the code, I found the loss was negative. Is it normal ?

**Comment by JunjH** [comment]
It's OK.

**Comment by Yidoudoujiang** [comment]
> It's OK.

And then I train the net as usual with minimizing the loss? (In this case, the absolute value will be maximum )

**Comment by JunjH** [comment]
You have misunderstood the loss, we just penalize l1 loss of depth in log space.
