### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by EasternH** [JunjH/Revisiting_Single_Depth_Estimation#32]
when I run train.py  （resnet50, 20epoch），the results were really bad, did I do something wrong?

PV nan
RV 0.0
FV nan
{'MSE': 9.498600609805607, 'RMSE': 3.081979982057899, 'ABS_REL': 1.0010360344469729, 'LG10': nan, 'MAE': 2.767429812603405, 'DELTA1': 0.6751519660337255, 'DELTA2': 0.6751519660337255, 'DELTA3': 0.6751519660337255}

**Comment by shezhi** [comment]
hello，Have you solved this problem？
