### ISSUE TITLE
File "demo.py", No module named 'senet'

### ISSUE THREAD

**Issue by ghost** [JunjH/Revisiting_Single_Depth_Estimation#33]
File "demo.py", line 5, in <module>
from models import modules, net, resnet, densenet, senet
File "C:\Users\DGRE\Revisiting_Single_Depth_Estimation\models\modules.py", line 9, in <module>
 import senet
ModuleNotFoundError: No module named 'senet'

**Comment by EkjotSingh898** [comment]
I'm facing the same issue, have you resolved this problem @iram01 ?

**Comment by ghost** [comment]
No

**Comment by GJdu** [comment]
This worked for me: 
change 
```import senet```
to
```from . import senet```
