### ISSUE TITLE
Negative numbers in loss

### ISSUE THREAD

**Issue by ustcxt** [JunjH/Revisiting_Single_Depth_Estimation#9]
Hello, thank you for sharing！
During training(python train.py),  I found that the value of loss function will have **a negative value.** 
In your code:
`
loss_depth = torch.log(torch.abs(output - depth) + 0.5).mean()
loss_dx = torch.log(torch.abs(output_grad_dx - depth_grad_dx) + 0.5).mean()
loss_dy = torch.log(torch.abs(output_grad_dy - depth_grad_dy) + 0.5).mean()
loss_normal = torch.abs(1 - cos(output_normal, depth_normal)).mean()
loss = loss_depth + loss_normal + (loss_dx + loss_dy)
`
The above three lines may have negative numbers due to the use of the log.
Excuse me, how did you solve it? Below is the loss of the initial iterations
Epoch: [0][0/8448]	Time 15.472 (15.472)	Loss 1.3450 (1.3450)
Epoch: [0][1/8448]	Time 1.345 (16.817)	Loss 1.0845 (1.2148)
Epoch: [0][2/8448]	Time 1.315 (18.132)	Loss 0.6541 (1.0279)
Epoch: [0][3/8448]	Time 1.317 (19.449)	Loss 0.5744 (0.9145)
Epoch: [0][4/8448]	Time 1.312 (20.762)	Loss 0.6484 (0.8613)
Epoch: [0][5/8448]	Time 1.327 (22.088)	Loss 0.7597 (0.8443)
Epoch: [0][6/8448]	Time 1.323 (23.411)	Loss 0.1689 (0.7479)
Epoch: [0][7/8448]	Time 1.321 (24.732)	Loss 0.4874 (0.7153)
Epoch: [0][8/8448]	Time 1.325 (26.057)	Loss 0.8373 (0.7289)
Epoch: [0][9/8448]	Time 1.323 (27.380)	Loss 0.5244 (0.7084)
Epoch: [0][10/8448]	Time 1.326 (28.707)	Loss 0.5639 (0.6953)
Epoch: [0][11/8448]	Time 1.322 (30.029)	Loss 0.5341 (0.6818)
Epoch: [0][12/8448]	Time 1.328 (31.357)	Loss 0.2113 (0.6456)
Epoch: [0][13/8448]	Time 1.326 (32.682)	Loss 0.6438 (0.6455)
Epoch: [0][14/8448]	Time 1.329 (34.011)	Loss 0.6620 (0.6466)
Epoch: [0][15/8448]	Time 1.330 (35.342)	Loss 0.1186 (0.6136)
Epoch: [0][16/8448]	Time 1.355 (36.697)	Loss 0.3656 (0.5990)
Epoch: [0][17/8448]	Time 1.334 (38.031)	Loss 0.2708 (0.5808)
Epoch: [0][18/8448]	Time 1.347 (39.378)	Loss 0.0469 (0.5527)
Epoch: [0][19/8448]	Time 1.361 (40.739)	Loss 0.2795 (0.5390)
Epoch: [0][20/8448]	Time 1.350 (42.089)	Loss 0.3525 (0.5301)
Epoch: [0][21/8448]	Time 1.343 (43.432)	Loss 0.7051 (0.5381)
Epoch: [0][22/8448]	Time 1.353 (44.786)	Loss 0.2296 (0.5247)
Epoch: [0][23/8448]	Time 1.373 (46.158)	Loss 0.2913 (0.5150)
Epoch: [0][24/8448]	Time 1.365 (47.523)	Loss 0.2287 (0.5035)
Epoch: [0][25/8448]	Time 1.438 (48.961)	Loss -0.3280 (0.4715)
Epoch: [0][26/8448]	Time 1.470 (50.432)	Loss -0.3840 (0.4398)
Epoch: [0][27/8448]	Time 1.437 (51.869)	Loss -0.2321 (0.4158)
Epoch: [0][28/8448]	Time 1.433 (53.302)	Loss -0.4591 (0.3857)
Epoch: [0][29/8448]	Time 1.437 (54.739)	Loss 0.1212 (0.3769)
Epoch: [0][30/8448]	Time 1.397 (56.136)	Loss -0.0415 (0.3634)
Epoch: [0][31/8448]	Time 1.454 (57.590)	Loss -0.0818 (0.3495)
Epoch: [0][32/8448]	Time 1.425 (59.015)	Loss -0.1126 (0.3354)
Epoch: [0][33/8448]	Time 1.354 (60.369)	Loss 0.0439 (0.3269)
Epoch: [0][34/8448]	Time 1.374 (61.742)	Loss -0.2679 (0.3099)
Epoch: [0][35/8448]	Time 1.446 (63.189)	Loss -0.2773 (0.2936)
Epoch: [0][36/8448]	Time 1.451 (64.640)	Loss -0.3940 (0.2750)
Epoch: [0][37/8448]	Time 1.414 (66.053)	Loss -0.3826 (0.2577)
Epoch: [0][38/8448]	Time 1.357 (67.410)	Loss -0.3142 (0.2430)
Epoch: [0][39/8448]	Time 1.345 (68.755)	Loss -0.3178 (0.2290)
Epoch: [0][40/8448]	Time 1.371 (70.126)	Loss -0.0380 (0.2225)
Epoch: [0][41/8448]	Time 1.368 (71.495)	Loss -0.4860 (0.2056)
Epoch: [0][42/8448]	Time 1.441 (72.936)	Loss -0.0844 (0.1989)
Epoch: [0][43/8448]	Time 1.466 (74.402)	Loss -0.0119 (0.1941)
Epoch: [0][44/8448]	Time 1.427 (75.829)	Loss -0.3213 (0.1826)
Epoch: [0][45/8448]	Time 1.375 (77.203)	Loss -0.3417 (0.1712)
Epoch: [0][46/8448]	Time 1.361 (78.564)	Loss -0.3974 (0.1591)
Epoch: [0][47/8448]	Time 1.401 (79.965)	Loss -0.1790 (0.1521)
Epoch: [0][48/8448]	Time 1.453 (81.418)	Loss -0.4916 (0.1390)
Epoch: [0][49/8448]	Time 1.433 (82.851)	Loss -0.0502 (0.1352)
Epoch: [0][50/8448]	Time 1.423 (84.274)	Loss -0.2328 (0.1280)
Epoch: [0][51/8448]	Time 1.449 (85.724)	Loss -0.1101 (0.1234)
Epoch: [0][52/8448]	Time 1.414 (87.138)	Loss -0.1645 (0.1179)
Epoch: [0][53/8448]	Time 1.361 (88.498)	Loss 0.3742 (0.1227)
Epoch: [0][54/8448]	Time 1.345 (89.843)	Loss -0.2367 (0.1162)
Epoch: [0][55/8448]	Time 1.390 (91.233)	Loss -0.4970 (0.1052)
Epoch: [0][56/8448]	Time 1.446 (92.679)	Loss -0.1625 (0.1005)
Epoch: [0][57/8448]	Time 1.415 (94.094)	Loss -0.7260 (0.0863)

**Comment by JunjH** [comment]
Yes, it will be negative since we calculate loss in log space. For better understanding, you can check how BP works. We found a little improvement of accuracy in log space.

**Comment by ustcxt** [comment]
Thank you very much for your reply.
I still have a question. I used **NVIDIA GTX 1080ti** during training, batch size=8, but there is out of memory. What graphics card are you using in the experiment? Thank you very much.

**Comment by JunjH** [comment]
We used  4 Tesla V100 and thus the batchsize was set 32.  You may set model = define_model(is_resnet=True, is_densenet=False, is_senet=False) or use a more smaller network.

**Comment by HuangGuoHui110** [comment]
> Thank you very much for your reply.
> I still have a question. I used **NVIDIA GTX 1080ti** during training, batch size=8, but there is out of memory. What graphics card are you using in the experiment? Thank you very much.
@ustcxt  you can try to  edit train.py to reset batch_size, the smaller batch_size would reduce GPU memory,hope this helps.
